SET(ROGII_MAJOR_VERSION 1)
SET(ROGII_MINOR_VERSION 1)
SET(ROGII_PATCH_VERSION 1)
SET(ROGII_REVISION_VERSION 7)

SET(ROGII_PKG_VERSION ${ROGII_MAJOR_VERSION}.${ROGII_MINOR_VERSION}.${ROGII_PATCH_VERSION}.${ROGII_REVISION_VERSION})
